<?php/*
	Sidebar
*/?>

			<img src="<?php echo $config->urls->templates?>images/div1.jpg">
			<nav>
				<ul>
					<li><a href="about.html">About</a></li>  
					<li><a href="robots.html">Robots</a></li>  
					<li><a href="sponsors.html">Sponsors</a></li>  
					<li><a href="community.html">Community</a></li> 
					<li><a href="blogs.html">Blog</a></li> 
					<li><a href="calendar.html">Calendar</a></li>  	
					<li><a href="resources.html">Resources</a></li>
				</ul>
			</nav>