<?php/*
	Sidebar -- include Resources/community?
*/?>

			<img src="<?php echo $config->urls->templates?>images/div1.jpg">
			<nav>
				<ul>
					<li><a href="<?php echo $config->urls->root; ?>members/">Team</a></li>  
					<li><a href="<?php echo $config->urls->root; ?>robots/">Robots</a></li>   
					<li><a href="<?php echo $config->urls->root; ?>blog/">Blog</a></li> 
					<li><a href="<?php echo $config->urls->root; ?>sponsors/">Sponsors</a></li> 
					<li><a href="<?php echo $config->urls->root; ?>calendar/">Calendar</a></li> 
					<li><a href="<?php echo $config->urls->root; ?>resources/">Resources</a></li>					
				</ul>
			</nav>